const threats=[
['Spoofing',16,'Uma identidade falsa para conquistar sua confiança. O atacante se passa por alguém ou por um serviço conhecido.','Confirme pedidos por um canal independente. Não confie apenas no nome ou na foto do remetente.'],
['Injeção de SQL',17,'Entradas inseguras em uma aplicação podem permitir que um invasor interfira nas consultas ao banco de dados.','Para quem desenvolve: use consultas parametrizadas e limite as permissões de acesso ao banco.'],
['Phishing',1,'Mensagens e páginas fraudulentas tentam convencer você a revelar senhas, dados ou realizar pagamentos.','Confira o endereço completo e acesse o serviço pelo aplicativo ou site oficial, sem usar o link recebido.'],
['Malware',2,'Programas maliciosos podem roubar informações, danificar arquivos ou bloquear o acesso aos seus dados.','Atualize o sistema e as ferramentas de proteção, use software legítimo e mantenha backups separados.'],
['Apps maliciosos',3,'Aplicativos que parecem úteis, mas abusam de permissões, coletam dados ou prejudicam seu dispositivo.','Prefira lojas oficiais, confira o desenvolvedor e as permissões. Avaliações positivas não garantem segurança.'],
['DDoS',4,'Muitas fontes enviam tráfego ao mesmo tempo para sobrecarregar um serviço e deixá-lo indisponível.','Para quem administra: utilize mitigação de DDoS, limites de requisições e monitoramento junto ao provedor.']
];
const protection=[['Confira quem está falando',6,'SPOOFING','Recebeu um pedido inesperado? Confirme com a pessoa por outro canal, usando um contato que você já conhece.'],['Instale com critério',13,'APPS MALICIOSOS','Verifique a origem, o desenvolvedor e as permissões. Mantenha seus aplicativos atualizados.'],['Pense antes de clicar',9,'PHISHING','Desconfie de urgência, ameaças e ofertas exageradas. Confira o endereço antes de informar qualquer dado.'],['Cuide dos seus dispositivos',12,'MALWARE','Mantenha a proteção e o sistema atualizados. Evite programas piratas e faça backups dos arquivos importantes.'],['Proteja o banco de dados',10,'INJEÇÃO DE SQL','Quem desenvolve deve usar consultas parametrizadas, permissões mínimas e componentes atualizados.'],['Prepare a infraestrutura',7,'DDoS','Quem mantém serviços deve combinar proteção especializada, monitoramento e um plano de resposta.']];
document.querySelector('#threat-grid').innerHTML=threats.map((t,i)=>`<article class="threat-card reveal"><div class="card-top"><img src="assets/${t[1]}.png" alt="" loading="lazy" width="43" height="43"><span>0${i+1}</span></div><h3>${t[0]}</h3><p>${t[2]}</p><details><summary>Como me proteger</summary><p>${t[3]}</p></details></article>`).join('');
document.querySelector('#protect-grid').innerHTML=protection.map((t,i)=>`<article class="protect-item reveal"><img src="assets/${t[1]}.png" alt="" loading="lazy" width="240" height="140"><h3><span>0${i+1}</span>${t[0]}</h3><span class="eyebrow dark" style="font-size:8px;margin-bottom:9px">${t[2]}</span><p>${t[3]}</p></article>`).join('');
if('IntersectionObserver' in window){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e))}
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}});
const checks=[...document.querySelectorAll('.checks input')];checks.forEach(c=>c.addEventListener('change',()=>{const count=checks.filter(x=>x.checked).length;document.querySelector('#check-count').textContent=count===4?'4 de 4 hábitos em dia. Continue cuidando dos seus dados!':`${count} de 4 hábitos em dia`;document.querySelector('#meter-fill').style.width=`${count*25}%`}));
let queued=false;function updateProgress(){const total=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading').style.width=`${total>0?scrollY/total*100:0}%`;queued=false}addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(updateProgress)}},{passive:true});addEventListener('resize',updateProgress);updateProgress();
